### ISSUE TITLE
Is it possible to include php55u-dbg anytime?

### ISSUE THREAD

**Issue by rnique** [iuscommunity-pkg/php55u#17]
Hi,
As you see this is not an issue or bug per se, but rather a "wishlist item". I see php56u-dbg is available, but there is not such package in php55u branch. Is there any technical impediment for that? If not, could you please include it in next release? This package is quite useful for tracking errors.

Best regards,
Roman.

**Comment by b-harper** [comment]
Hey @rnique,

Thanks for taking the time to submit this issue.  Looking over PHP's documentation, [dbg was introduced in as internal debugger in 5.6][0].  Seeing that PHP 5.5 is almost [EOL][1], we are no longer taking new package request for PHP 5.5.  I would highly recommend migrating off PHP 5.5.  In the mean time, we do have php55u-pecl-xdebug that might fit your needs.

-Ben

[0]: http://php.net/manual/en/debugger-about.php
[1]: https://github.com/iuscommunity/announce/issues/1
